proyecto/casaeventos/Empleado/urls.py
from django.urls import include,path
from home.views import Home
from Empleado.views import ListEmpleados, InsertarEmpleado
from Empleado.views import EditarEmpleado, BorrarEmpleado, InsertarPabellon
from .views import ListPabellones, EditarPabellon, BorrarPabellon
from .views import InsertarEvento, ListEventos, EditarEvento, BorrarEvento, InsertarArtista, ListArtitas
from .views import EditarArtista, BorrarArtista, InsertarDiseñador, ListDiseñadores, EditarDiseñador, BorrarDiseñador
from .views import InsertarDesfile, ListDesfiles, EditarDesfile, BorrarDesfile
urlpatterns=[
    #Empleados
    path('empleados',ListEmpleados.as_view(),name='listar_empleados'),
    path('empleados/new',InsertarEmpleado.as_view(),name='insertar_empleados'),
    path('empleados/edit/<int:pk>',EditarEmpleado.as_view(),name='editar_empleados'),
    path('empleados/delete/<int:pk>',BorrarEmpleado.as_view(),name='eliminar_empleados'),

    #Pabellones
    path('pabellones',ListPabellones.as_view(),name='listar_pabellones'),
    path('pabellones/new',InsertarPabellon.as_view(),name='insertar_pabellones'),
    path('pabellones/edit/<int:pk>',EditarPabellon.as_view(),name='editar_pabellones'),
    path('pabellones/delete/<int:pk>',BorrarPabellon.as_view(),name='eliminar_pabellones'),

    #Eventos
    path('eventos',ListEventos.as_view(),name='listar_eventos'),
    path('eventos/new',InsertarEvento.as_view(),name='insertar_eventos'),
    path('eventos/edit/<int:pk>',EditarEvento.as_view(),name='editar_eventos'),
    path('eventos/delete/<int:pk>',BorrarEvento.as_view(),name='eliminar_eventos'),

    #Artistas
    path('artistas',ListArtitas.as_view(),name='listar_artistas'),
    path('artistas/new',InsertarArtista.as_view(),name='insertar_artistas'),
    path('artistas/edit/<int:pk>',EditarArtista.as_view(),name='editar_artistas'),
    path('artistas/delete/<int:pk>',BorrarArtista.as_view(),name='eliminar_artistas'),

    #Diseñadores
    path('diseñadores',ListDiseñadores.as_view(),name='listar_diseñadores'),
    path('diseñadores/new',InsertarDiseñador.as_view(),name='insertar_diseñadores'),
    path('diseñadores/edit/<int:pk>',EditarDiseñador.as_view(),name='editar_diseñadores'),
    path('diseñadores/delete/<int:pk>',BorrarDiseñador.as_view(),name='eliminar_diseñadores'),

    #Desfiles
    path('desfiles',ListDesfiles.as_view(),name='listar_desfiles'),
    path('desfiles/new',InsertarDesfile.as_view(),name='insertar_desfiles'),
    path('desfiles/edit/<int:pk>',EditarDesfile.as_view(),name='editar_desfiles'),
    path('desfiles/delete/<int:pk>',BorrarDesfile.as_view(),name='eliminar_desfiles'),
]

proyecto/casaeventos/casaeventos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include(('home.urls','home'),namespace='home')),
    path('home',include(('home.urls','home'),namespace='home')),
    path('admin/', admin.site.urls),
    path('empleados',include(('Empleado.urls','Empleado'),namespace='empleados')),
]

proyecto/casaeventos/home/urls.py
from django.urls import include,path
from home.views import Home
urlpatterns=[
    path('',Home.as_view(),name='home')
]

proyecto/casaeventos/Empleado/models.py
from django.db import models

# Create your models here.
class Empleado(models.Model):
    nombre=models.CharField(
        max_length=40,
    )
    apellido=models.CharField(
        max_length=40,
    )
    correo=models.CharField(
        max_length=50,
    )
    universidad=models.CharField(
        max_length=50,
    )
    celular=models.IntegerField(

    )
    def __str__(self):
        return self.apellido + " " +self.nombre
    def save(self):
        self.nombre = self.nombre.upper()
        self.apellido = self.apellido.upper()
        self.universidad = self.universidad.upper()
        super(Empleado,self).save()
    class Meta:
        verbose_name_plural="Empleados"

class Pabellon(models.Model):
    nombre=models.CharField(
        max_length=50,
    )
    telefono=models.IntegerField(

    )
    Empleado=models.ForeignKey(
        Empleado, 
        on_delete=models.CASCADE
    )
    def __str__(self):
        return '{}:{}'.format(Pabellon, self.nombre)
    def save(self):
        self.nombre = self.nombre.upper()
        super(Pabellon,self).save()
    class Meta:
        verbose_name_plural="Pabellones"

class Evento(models.Model):
    nombre=models.CharField(
        max_length=50,
    )
    fechaInicio=models.DateTimeField(

    )
    fechaFin=models.DateTimeField(

    )
    Empleado=models.ForeignKey(
        Empleado, 
        on_delete=models.CASCADE
    )
    presupuesto=models.IntegerField(

    )
    def __str__(self):
        return '{}:{}'.format(Evento, self.nombre)
    def save(self):
        self.nombre = self.nombre.upper()
        super(Evento,self).save()
    class Meta:
        verbose_name_plural="Eventos"

class Artista(models.Model):
    nombre=models.CharField(
        max_length=50,
    )
    generoMusical=models.CharField(
        max_length=30,
    )
    rol=models.CharField(
        max_length=10,
    )
    def __str__(self):
        return '{}:{}'.format(Artista, self.nombre)
    def save(self):
        self.nombre = self.nombre.upper()
        super(Artista,self).save()
    class Meta:
        verbose_name_plural="Artistas"

class Diseñador(models.Model):
    nombre=models.CharField(
        max_length=50,
    )
    pasaporte=models.IntegerField(
        
    )
    paisOrigen=models.CharField(
        max_length=50,
    )
    def __str__(self):
        return '{}:{}'.format(Diseñador, self.nombre)
    def save(self):
        self.nombre = self.nombre.upper()
        super(Diseñador,self).save()
    class Meta:
        verbose_name_plural="Diseñadores"

class Desfile(models.Model):
    nombre=models.CharField(
        max_length=50,
    )
    fecha=models.DateTimeField(

    )
    coleccion=models.CharField(
        max_length=50,
    )
    Artista=models.ForeignKey(
        Artista, 
        on_delete=models.CASCADE
    )
    Diseñador=models.ForeignKey(
        Diseñador, 
        on_delete=models.CASCADE
    )
    def __str__(self):
        return '{}:{}'.format(Desfile, self.nombre)
    def save(self):
        self.nombre = self.nombre.upper()
        super(Desfile,self).save()
    class Meta:
        verbose_name_plural="Desfiles"

proyecto/casaeventos/Empleado/forms.py
from django import forms
from .models import Empleado, Pabellon, Evento, Artista, Diseñador, Desfile
class EmpleadoForm(forms.ModelForm):
    class Meta:
        model=Empleado
        fields=['nombre','apellido','correo','universidad','celular']
        labels={'nombre':'Ingese su nombre',
        'apellido':'Ingese su apellido',
        'correo':'Ingese su correo',
        'universidad':'Ingese su Univesidad engresada',
        'celular':'Ingese su numero celular', 
        }
        widget={
            'nombre':forms.TextInput(),
            'apellido':forms.TextInput(),
            'correo':forms.TextInput(),
            'universidad':forms.TextInput(),
            'nombre':forms.NumberInput(),
        }
        def __init__(self,*args,**kgwards):
            super().__init__(*args,**kgwards)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })
class PabellonForm(forms.ModelForm):
    class Meta:
        model=Pabellon
        fields=['nombre','telefono','Empleado']
        labels={'nombre':'Ingrese el nombre',
        'telefono':'Ingrese el numero telefonico',
        'Empleado':'Selecione al Empleado',
        }
        widget={
            'nombre':forms.TextInput(),
            'telefono':forms.NumberInput(),
        }
        def __init__(self,*args,**kgwards):
            super().__init__(*args,**kgwards)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })
class EventoForm(forms.ModelForm):
    class Meta:
        model=Evento
        fields=['nombre','fechaInicio','fechaFin','Empleado','presupuesto']
        labels={'nombre':'Ingrese el nombre',
        'fechaInicio':'Ingrese La fecha de inicio',
        'fechaFin':'Ingrese la fecha de finalizacion',
        'Empleado':'Selecione el Empleado',
        'presupuesto':'Ingrese el presupuesto',
        }
        widget={
            'nombre':forms.TextInput(),
            'fechaInicio':forms.DateInput(),
            'fechaFin':forms.DateInput(),
            'presupuesto':forms.NumberInput(),

        }
        def __init__(self,*args,**kgwards):
            super().__init__(*args,**kgwards)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })
class ArtistaForm(forms.ModelForm):
    class Meta:
        model=Artista
        fields=['nombre','generoMusical','rol']
        labels={'nombre':'Ingrese el nombre',
        'generoMusical':'Ingrese el Genero Musical',
        'rol':'Ingrese el rol del Artista',
        }
        widget={
            'nombre':forms.TextInput(),
            'generoMusical':forms.TextInput(),
            'rol':forms.TextInput(),
        }
class DiseñadorForm(forms.ModelForm):
    class Meta:
        model=Diseñador
        fields=['nombre','pasaporte','paisOrigen']
        labels={'nombre':'Ingrese el nombre',
        'pasaporte':'Ingrese el numero de pasaporte',
        'paisOrigen':'Ingrese el pais de origen',
        }
        widget={
            'nombre':forms.TextInput(),
            'pasaporte':forms.NumberInput(),
            'paisOrigen':forms.TextInput(),
        }
class DesfileForm(forms.ModelForm):
    class Meta:
        model=Desfile
        fields=['nombre','fecha','coleccion','Artista','Diseñador']
        labels={'nombre':'Ingrese el nombre',
        'fecha':'Ingrese la fecha',
        'coleccion':'Ingrese el nombre de la coleccion',
        'Artista':'Selecione al artista',
        'Diseñador':'Selecione al diseñador',
        }
        widget={
            'nombre':forms.TextInput(),
            'fecha':forms.DateInput(),
            'coleccion':forms.TextInput(),
        }
        def __init__(self,*args,**kgwards):
            super().__init__(*args,**kgwards)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })

proyecto/casaeventos/Empleado/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from Empleado.models import Empleado, Pabellon, Evento, Artista, Diseñador, Desfile
from .forms import EmpleadoForm, PabellonForm, EventoForm, ArtistaForm, DiseñadorForm, DesfileForm
# Create your views here.
class ListEmpleados(generic.ListView):
    model=Empleado
    template_name="listar_empleados.html"
    context_object_name="emp"
class InsertarEmpleado(generic.CreateView):
    model=Empleado
    template_name="empleado_form.html"
    form_class=EmpleadoForm
    success_url=reverse_lazy("Empleado:listar_empleados")
class EditarEmpleado(generic.UpdateView):
    model=Empleado
    template_name="empleado_form.html"
    form_class=EmpleadoForm
    success_url=reverse_lazy("Empleado:listar_empleados")
class BorrarEmpleado(generic.DeleteView):
    model=Empleado
    template_name="borrar_empleado.html"
    context_object_name="emp"
    success_url=reverse_lazy("Empleado:listar_empleados")


class ListPabellones(generic.ListView):
    model=Pabellon
    template_name="listar_pabellones.html"
    context_object_name="pab"
class InsertarPabellon(generic.CreateView):
    model=Pabellon
    template_name="pabellon_form.html"
    form_class=PabellonForm
    success_url=reverse_lazy("Empleado:listar_pabellones")
class EditarPabellon(generic.UpdateView):
    model=Pabellon
    template_name="pabellon_form.html"
    form_class=PabellonForm
    success_url=reverse_lazy("Empleado:listar_pabellones")
class BorrarPabellon(generic.DeleteView):
    model=Pabellon
    template_name="borrar_pabellon.html"
    context_object_name="pab"
    success_url=reverse_lazy("Empleado:listar_pabellones")


class ListEventos(generic.ListView):
    model=Evento
    template_name="listar_eventos.html"
    context_object_name="eve"
class InsertarEvento(generic.CreateView):
    model=Evento
    template_name="evento_form.html"
    form_class=EventoForm
    success_url=reverse_lazy("Empleado:listar_eventos")
class EditarEvento(generic.UpdateView):
    model=Evento
    template_name="evento_form.html"
    form_class=EventoForm
    success_url=reverse_lazy("Empleado:listar_eventos")
class BorrarEvento(generic.DeleteView):
    model=Evento
    template_name="borrar_evento.html"
    context_object_name="eve"
    success_url=reverse_lazy("Empleado:listar_eventos")


class ListArtitas(generic.ListView):
    model=Artista
    template_name="listar_artistas.html"
    context_object_name="art"
class InsertarArtista(generic.CreateView):
    model=Artista
    template_name="artista_form.html"
    form_class=ArtistaForm
    success_url=reverse_lazy("Empleado:listar_artistas")
class EditarArtista(generic.UpdateView):
    model=Artista
    template_name="artista_form.html"
    form_class=ArtistaForm
    success_url=reverse_lazy("Empleado:listar_artistas")
class BorrarArtista(generic.DeleteView):
    model=Artista
    template_name="borrar_artista.html"
    context_object_name="art"
    success_url=reverse_lazy("Empleado:listar_artistas")


class ListDiseñadores(generic.ListView):
    model=Diseñador
    template_name="listar_diseñadores.html"
    context_object_name="dis"
class InsertarDiseñador(generic.CreateView):
    model=Diseñador
    template_name="diseñador_form.html"
    form_class=DiseñadorForm
    success_url=reverse_lazy("Empleado:listar_artistas")
class EditarDiseñador(generic.UpdateView):
    model=Diseñador
    template_name="diseñador_form.html"
    form_class=DiseñadorForm
    success_url=reverse_lazy("Empleado:listar_diseñadores")
class BorrarDiseñador(generic.DeleteView):
    model=Diseñador
    template_name="borrar_diseñador.html"
    context_object_name="dis"
    success_url=reverse_lazy("Empleado:listar_diseñadores")


class ListDesfiles(generic.ListView):
    model=Desfile
    template_name="listar_desfiles.html"
    context_object_name="des"
class InsertarDesfile(generic.CreateView):
    model=Desfile
    template_name="desfile_form.html"
    form_class=DesfileForm
    success_url=reverse_lazy("Empleado:listar_artistas")
class EditarDesfile(generic.UpdateView):
    model=Desfile
    template_name="desfile_form.html"
    form_class=DesfileForm
    success_url=reverse_lazy("Empleado:listar_desfiles")
class BorrarDesfile(generic.DeleteView):
    model=Desfile
    template_name="borrar_desfile.html"
    context_object_name="des"
    success_url=reverse_lazy("Empleado:listar_desfiles")

proyecto/casaeventos/Empleado/templates/artista_form.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<form method="post" >
    <div class="panel panel-default">
    <h1>Registre el Artista</h1>
    </div>  {% csrf_token %}
    <div class="form-group">
        {{form.as_p}}
    </div>
        <button type="submit" class="btn btn-dark">
            <span class="fa fa-save">
                Registrar
            </span>
        </button>
    </div>
</form>
{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/borrar_artista.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<form method="post">
    <div class="panel panel-dafault">
        <div class="panel heading">
            Eliminar Artista
        </div>
        <div class="panel-body">
            {% csrf_token %}
            <div class="alert alert-success">
                Eliminar {{art.nombre}} 
            </div>
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-delete">
                    Eliminar 
                </span>
            </button>
            <a href="{% url 'empleados:listar_eventos' %}" class="btn btn-success">
                <span>Cancelar</span>
            </a>
        </div>
    </div>
</form>


{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/borrar_desfile.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<form method="post">
    <div class="panel panel-dafault">
        <div class="panel heading">
            Eliminar Desfile
        </div>
        <div class="panel-body">
            {% csrf_token %}
            <div class="alert alert-success">
                Eliminar {{des.nombre}} 
            </div>
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-delete">
                    Eliminar 
                </span>
            </button>
            <a href="{% url 'empleados:listar_eventos' %}" class="btn btn-success">
                <span>Cancelar</span>
            </a>
        </div>
    </div>
</form>


{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/borrar_diseñador.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<form method="post">
    <div class="panel panel-dafault">
        <div class="panel heading">
            Eliminar Diseñador
        </div>
        <div class="panel-body">
            {% csrf_token %}
            <div class="alert alert-success">
                Eliminar {{dis.nombre}} 
            </div>
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-delete">
                    Eliminar 
                </span>
            </button>
            <a href="{% url 'empleados:listar_eventos' %}" class="btn btn-success">
                <span>Cancelar</span>
            </a>
        </div>
    </div>
</form>


{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/borrar_empleado.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<form method="post">
    <div class="panel panel-dafault">
        <div class="panel heading">
            Eliminar Empleado
        </div>
        <div class="panel-body">
            {% csrf_token %}
            <div class="alert alert-success">
                Eliminar {{emp.nombre}} {{emp.apellido}}
            </div>
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-delete">
                    Eliminar 
                </span>
            </button>
            <a href="{% url 'empleados:listar_empleados' %}" class="btn btn-success">
                <span>Cancelar</span>
            </a>
        </div>
    </div>
</form>


{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/borrar_evento.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<form method="post">
    <div class="panel panel-dafault">
        <div class="panel heading">
            Eliminar Evento
        </div>
        <div class="panel-body">
            {% csrf_token %}
            <div class="alert alert-success">
                Eliminar {{eve.nombre}} 
            </div>
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-delete">
                    Eliminar 
                </span>
            </button>
            <a href="{% url 'empleados:listar_eventos' %}" class="btn btn-success">
                <span>Cancelar</span>
            </a>
        </div>
    </div>
</form>


{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/borrar_pabellon.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<form method="post">
    <div class="panel panel-dafault">
        <div class="panel heading">
            Eliminar Pabellon
        </div>
        <div class="panel-body">
            {% csrf_token %}
            <div class="alert alert-success">
                Eliminar {{pab.nombre}} 
            </div>
            <button type="submit" class="btn btn-danger">
                <span class="fa fa-delete">
                    Eliminar 
                </span>
            </button>
            <a href="{% url 'empleados:listar_pabellones' %}" class="btn btn-success">
                <span>Cancelar</span>
            </a>
        </div>
    </div>
</form>


{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/desfile_form.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<form method="post" >
    <div class="panel panel-default">
    <h1>Registre el Desfile</h1>
    </div>  {% csrf_token %}
    <div class="form-group">
        {{form.as_p}}
    </div>
        <button type="submit" class="btn btn-dark">
            <span class="fa fa-save">
                Registrar
            </span>
        </button>
    </div>
</form>
{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/diseñador_form.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<form method="post" >
    <div class="panel panel-default">
    <h1>Registre el Diseñador</h1>
    </div>  {% csrf_token %}
    <div class="form-group">
        {{form.as_p}}
    </div>
        <button type="submit" class="btn btn-dark">
            <span class="fa fa-save">
                Registrar
            </span>
        </button>
    </div>
</form>
{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/empleado_form.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<form method="post" >
    <div class="panel panel-default">
    <h1>Registre el empleado</h1>
    </div>  {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="id_nombre">Ingese su nombre:</label> 
            <input type="text" class="form-control" name="nombre" maxlength="40" required id="id_nombre" placeholder="Ingrese su nombre">
        </div>
        <div class="form-group col-md-6">
            <label for="id_apellido">Ingese su apellido:</label> 
            <input type="text" class="form-control" name="apellido" maxlength="40" required id="id_apellido" placeholder="Ingrese su apellido">
        </div>
    </div>
    <div class="form-group">
        <label for="id_correo">Ingese su correo:</label>
        <input type="email" class="form-control" name="correo" maxlength="50" required id="id_correo" placeholder="Ingrese su correo">
    </div>
    <div class="form-row">
        <div class="form-group col-md-8">
            <label for="id_universidad">Ingese su Univesidad engresada:</label>
            <input type="text" class="form-control" name="universidad" maxlength="50" required id="id_universidad" placeholder="Ingrese su Universidad engresada">
        </div>
        <div class="form-group col-md-4">
            <label for="id_celular">Ingese su numero celular:</label> 
            <input type="number" class="form-control" name="celular" required id="id_celular" placeholder="Ingrese su numero celular">
        </div>
    </div>
        <button type="submit" class="btn btn-dark">
            <span class="fa fa-save">
                Registrar
            </span>
        </button>
    </div>
</form>
{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/evento_form.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<form method="post" >
    <div class="panel panel-default">
    <h1>Registre el Evento</h1>
    </div>  {% csrf_token %}
    <div class="form-group">
        {{form.as_p}}
    </div>
        <button type="submit" class="btn btn-dark">
            <span class="fa fa-save">
                Registrar
            </span>
        </button>
    </div>
</form>
{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/listar_desfiles.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<div class="panel-body">
    <table width="100" class="table table-striped table-bordered table-hover table-dark" id="dataTables">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Nombre
                </th>
                <th>
                    Fecha
                </th>
                <th>
                    Coleccion
                </th>
                <th>
                    Artista
                </th>
                <th>
                    Diseñador
                </th>
                <th>
                    Acciones
                </th>
            </tr>
        </thead>
        <tbody class="bg-info">
            {% for item in des %}
                <tr>
                    <td>
                        {{item.id}}
                    </td>
                    <td>
                        {{item.nombre}}
                    </td>
                    <td>
                        {{item.fecha}}
                    </td>
                    <td>
                        {{item.coleccion}}
                    </td>
                    <td>
                        {{item.Artista}}
                    </td>
                    <td>
                        {{item.Diseñador}}
                    </td>
                    <td>
                        <a href="{% url 'empleados:editar_desfiles' item.id %}" class="btn btn-primary btn-circle">
                            <span class="fa fa-edit">
                                editar
                            </span>
                        </a>
                        <a href="{% url 'empleados:eliminar_desfiles' item.id %}" class="btn btn-danger btn-circle">
                            <span class="fa fa-delete">
                                eliminar
                            </span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/listar_diseñadores.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<div class="panel-body">
    <table width="100" class="table table-striped table-bordered table-hover table-dark" id="dataTables">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Nombres
                </th>
                <th>
                    Pasaporte
                </th>
                <th>
                    Pais de Origen
                </th>
                <th>
                    Acciones
                </th>
            </tr>
        </thead>
        <tbody class="bg-warning">
            {% for item in dis %}
                <tr>
                    <td>
                        {{item.id}}
                    </td>
                    <td>
                        {{item.nombre}}
                    </td>
                    <td>
                        {{item.pasaporte}}
                    </td>
                    <td>
                        {{item.paisOrigen}}
                    </td>
                    <td>
                        <a href="{% url 'empleados:editar_diseñadores' item.id %}" class="btn btn-primary btn-circle">
                            <span class="fa fa-edit">
                                editar
                            </span>
                        </a>
                        <a href="{% url 'empleados:eliminar_diseñadores' item.id %}" class="btn btn-danger btn-circle">
                            <span class="fa fa-delete">
                                eliminar
                            </span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock cuerpo %}

proyecto/casaeventos/Empleado/templates/listar_empleados.html
{% extends 'base/base.html' %}
{% block cuerpo %}
<div class="panel-body">
    <table width="100" class="table table-striped table-bordered table-hover table-dark" id="dataTables">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Nombres
                </th>
                <th>
                    Apellidos
                </th>
                <th>
                    Correo
                </th>
                <th>
                    Universidad
                </th>
                <th>
                    Celular
                </th>
                <th>
                    Acciones
                </th>
            </tr>
        </thead>
        <tbody class="bg-warning">
            {% for item in emp %}
                <tr>
                    <td>
                        {{item.id}}
                    </td>
                    <td>
                        {{item.nombre}}
                    </td>
                    <td>
                        {{item.apellido}}
                    </td>
                    <td>
                        {{item.correo}}
                    </td>
                    <td>
                        {{item.universidad}}
                    </td>
                    <td>
                        {{item.celular}}
                    </td>
                    <td>
                        <a href="{% url 'empleados:editar_empleados' item.id %}" class="btn btn-primary btn-circle">
                            <span class="fa fa-edit">
                                editar
                            </span>
                        </a>
                        <a href="{% url 'empleados:eliminar_empleados' item.id %}" class="btn btn-danger btn-circle">
                            <span class="fa fa-delete">
                                eliminar
                            </span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock cuerpo %}