proyecto/casaeventos/Empleado/urls.py
from django.urls import include,path
from home.views import Home
from Empleado.views import ListEmpleados, InsertarEmpleado
from Empleado.views import EditarEmpleado, BorrarEmpleado, InsertarPabellon
from .views import ListPabellones, EditarPabellon, BorrarPabellon
from .views import InsertarEvento, ListEventos, EditarEvento, BorrarEvento, InsertarArtista, ListArtitas
from .views import EditarArtista, BorrarArtista, InsertarDiseñador, ListDiseñadores, EditarDiseñador, BorrarDiseñador
from .views import InsertarDesfile, ListDesfiles, EditarDesfile, BorrarDesfile
urlpatterns=[
    #Empleados
    path('empleados',ListEmpleados.as_view(),name='listar_empleados'),
    path('empleados/new',InsertarEmpleado.as_view(),name='insertar_empleados'),
    path('empleados/edit/<int:pk>',EditarEmpleado.as_view(),name='editar_empleados'),
    path('empleados/delete/<int:pk>',BorrarEmpleado.as_view(),name='eliminar_empleados'),

    #Pabellones
    path('pabellones',ListPabellones.as_view(),name='listar_pabellones'),
    path('pabellones/new',InsertarPabellon.as_view(),name='insertar_pabellones'),
    path('pabellones/edit/<int:pk>',EditarPabellon.as_view(),name='editar_pabellones'),
    path('pabellones/delete/<int:pk>',BorrarPabellon.as_view(),name='eliminar_pabellones'),

    #Eventos
    path('eventos',ListEventos.as_view(),name='listar_eventos'),
    path('eventos/new',InsertarEvento.as_view(),name='insertar_eventos'),
    path('eventos/edit/<int:pk>',EditarEvento.as_view(),name='editar_eventos'),
    path('eventos/delete/<int:pk>',BorrarEvento.as_view(),name='eliminar_eventos'),

    #Artistas
    path('artistas',ListArtitas.as_view(),name='listar_artistas'),
    path('artistas/new',InsertarArtista.as_view(),name='insertar_artistas'),
    path('artistas/edit/<int:pk>',EditarArtista.as_view(),name='editar_artistas'),
    path('artistas/delete/<int:pk>',BorrarArtista.as_view(),name='eliminar_artistas'),

    #Diseñadores
    path('diseñadores',ListDiseñadores.as_view(),name='listar_diseñadores'),
    path('diseñadores/new',InsertarDiseñador.as_view(),name='insertar_diseñadores'),
    path('diseñadores/edit/<int:pk>',EditarDiseñador.as_view(),name='editar_diseñadores'),
    path('diseñadores/delete/<int:pk>',BorrarDiseñador.as_view(),name='eliminar_diseñadores'),

    #Desfiles
    path('desfiles',ListDesfiles.as_view(),name='listar_desfiles'),
    path('desfiles/new',InsertarDesfile.as_view(),name='insertar_desfiles'),
    path('desfiles/edit/<int:pk>',EditarDesfile.as_view(),name='editar_desfiles'),
    path('desfiles/delete/<int:pk>',BorrarDesfile.as_view(),name='eliminar_desfiles'),
]

proyecto/casaeventos/casaeventos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include(('home.urls','home'),namespace='home')),
    path('home',include(('home.urls','home'),namespace='home')),
    path('admin/', admin.site.urls),
    path('empleados',include(('Empleado.urls','Empleado'),namespace='empleados')),
]

proyecto/casaeventos/home/urls.py
from django.urls import include,path
from home.views import Home
urlpatterns=[
    path('',Home.as_view(),name='home')
]

proyecto/casaeventos/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <title>{% block title %} Casa de Eventos {% endblock %}</title>

    <!--Scripts CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Casa Eventos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Eventos
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'empleados:insertar_eventos' %}">Crear Evento</a>
                <a class="dropdown-item" href="{% url 'empleados:listar_eventos' %}">Lista Eventos</a>
              </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Desfile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'empleados:insertar_desfiles' %}">Crear Desfile</a>
                  <a class="dropdown-item" href="{% url 'empleados:listar_desfiles' %}">Lista Desfiles</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Pabellon
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'empleados:insertar_pabellones' %}">Crear Pabellon</a>
                  <a class="dropdown-item" href="{% url 'empleados:listar_pabellones' %}">Lista Pabellon</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Usuarios
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'empleados:insertar_empleados' %}">Crear Empleado</a>
                  <a class="dropdown-item" href="{% url 'empleados:listar_empleados' %}">Lista Empleados</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'empleados:insertar_diseñadores' %}">Crear Diseñador</a>
                  <a class="dropdown-item" href="{% url 'empleados:listar_diseñadores' %}">Lista Diseñadores</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'empleados:insertar_artistas' %}">Crear Artista</a>
                  <a class="dropdown-item" href="{% url 'empleados:listar_artistas' %}">Lista Artistas</a>
                </div>
              </li>
          </ul>
        </div>
      </nav>
</head>
<body>

    {% block cuerpo %}

    {% endblock cuerpo %}
    
</body>

<!--Scripts JS-->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</html>